services:
  server:
    build: ./server
    ports:
      - "50051"

  vote-manager:
    build: ./vote-manager
    ports:
      - "50051"

  envoy:
    image: envoyproxy/envoy:v1.29-latest
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./web/descriptors/services.pb:/etc/envoy/services.pb
    depends_on:
      - server

  web:
    build: ./web
    ports:
      - "80:3000"
    depends_on:
      - envoy
