[package]
name = "vote-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.11"
tokio = { version = "1", features = ["full"] }
prost = "0.12"
sled = "0.34.7"

[build-dependencies]
tonic-build = { version = "0.11", features = ["prost"] }
